export const theme = {
  colors: {
    primary: "#0D2C6B",
    primaryDark: "#081E4A",
    primarySoft: "#EAF0FF",
    primaryMuted: "#BED0FF",
    accent: "#2563EB",
    accentSoft: "#EFF6FF",
    navy: "#0D2C6B",
    navyMid: "#1A3F8F",
    navyDeep: "#081E4A",
    blue: "#2563EB",
    blueSoft: "#EFF6FF",
    teal: "#0F9D8A",
    tealSoft: "#EAFBF8",
    gold: "#F59E0B",
    goldSoft: "#FFFBEB",
    orange: "#F28B3C",
    orangeSoft: "#FFF4E8",
    rose: "#E11D48",
    roseSoft: "#FFF1F2",
    plum: "#7C3AED",
    plumSoft: "#F5F3FF",
    green: "#16A34A",
    greenSoft: "#ECFDF5",
    red: "#DC2626",
    redSoft: "#FEF2F2",
    white: "#FFFFFF",
    text: "#0F172A",
    muted: "#64748B",
    mutedLight: "#94A3B8",
    border: "#E2E8F0",
    borderLight: "#EEF2F7",
    surface: "#F8FAFF",
    surfaceAlt: "#F1F5F9",
    surfaceWarm: "#FFFDF4",
    surfaceCard: "#FFFFFF",
    background: "#F0F4FF"
  },
  radius: {
    xl: 30,
    lg: 22,
    md: 18,
    sm: 14,
    xs: 10
  },
  shadow: {
    shadowColor: "#0F172A",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4
  },
  shadowMd: {
    shadowColor: "#0F172A",
    shadowOpacity: 0.14,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 12 },
    elevation: 7
  }
};
